### ISSUE TITLE
Usage instructions do not work for `dist` case

### ISSUE THREAD

**Issue by dakur** [jiripudil/Naja#1]
I used the [dist file](https://github.com/jiripudil/Naja/blob/master/dist/Naja.js), imported it into my project via `script` tag and then used `document.addEventListener('DOMContentLoaded', naja.initialize.bind(naja));`, but the console is saying: `TypeError: naja.initialize is undefined`.

![snimek z 2017-06-17 11 55 00](https://user-images.githubusercontent.com/9862581/27252005-d522f424-5353-11e7-8b34-2839128e81e6.png)

**Comment by jiripudil** [comment]
Confirmed, thanks for the report.

Note to self: [this](https://github.com/webpack/webpack/issues/3929#issuecomment-302847825) should help, and, as soon as Webpack 3 is out, [this](https://github.com/webpack/webpack/commit/de8fc51a6fe2aff3ea3a1c24d34d429897c3b694).
