### ISSUE TITLE
Formular a auto submit

### ISSUE THREAD

**Issue by jaygridley** [jiripudil/Naja#11]
Ahoj,

lze nejak jednoduse implementovat ve spojeni s knihovnou auto submit formulare, napr. na change/input inputu formulare? Zkousel jsem vyvolat nad formularem explicitne submit, ale to mi pak nechytne ajax. Resil jiz nekdo?

**Comment by jiripudil** [comment]
Prohlížeč bohužel při explicitním zavolání `form.submit()` nevyvolá událost `submit`, na kterou Naja naslouchá. Řešili a vyřešili jsme to zhruba takto:

```js
form.dispatchEvent(createEvent('submit', {bubbles: true, cancelable: true}));

const createEvent = (type, {bubbles, cancelable}) => {
    if (typeof(Event) === 'function') {
        return new Event(type, {bubbles, cancelable}});
    }

    // IE does not support Event constructor
    const event = document.createEvent('Event');
    event.initEvent(type, bubbles, cancelable);
    return event;
};
```

Připadá mi to hodně krkolomné, ale ještě jsem nepřemýšlel nad tím, jak to udělat hezčí. Možná by stačilo přidat helper metodu `naja.uiHandler.submitForm(form)` (a případně `naja.uiHandler.clickElement(el)`)?

**Comment by jaygridley** [comment]
Hlasuju pro helper metodu.

**Comment by jiripudil** [comment]
Taky mi to dává smysl. O víkendu se na to podívám.

**Comment by jiripudil** [comment]
Vydal jsem 1.4.0, kde je tato úprava obsažená.
