### ISSUE TITLE
Mention example on TrainIT

### ISSUE THREAD

**Issue by f3l1x** [jiripudil/Naja#13]
Hi, 

would you like to mention this example (https://github.com/trainit/2018-03-nette-webpack)?

It might be good for both sides.

**Comment by jiripudil** [comment]
Done, thanks for the suggestion :)

**Comment by f3l1x** [comment]
Thank you.

**Comment by f3l1x** [comment]
Tiny detail, it seems that mention does not create a link in README.

**Comment by jiripudil** [comment]
Oh. Thanks for pointing out.
