### ISSUE TITLE
FormsHandler: configurable nette-forms reference

### ISSUE THREAD

**Issue by jiripudil** [jiripudil/Naja#14]
FormsHandler currently assumes that nette-forms is located in `window.Nette`; it'd make sense to make this configurable, because nette-forms might be loaded as a module e.g. via webpack:

```js
import netteForms from 'nette-forms';
naja.formsHandler.netteForms = netteForms;
```

It should be undefined by default, in which case FormsHandler would fall back to `window.Nette`.

**Comment by f3l1x** [comment]
Good job.
