### ISSUE TITLE
Reload extensions s manuálním dispatchem

### ISSUE THREAD

**Issue by daarxwalker** [jiripudil/Naja#16]
Pokud snippety přenačtu jinak než Najou (např. Nittro), tak klasické naja.load() pro přenačtení s manuálním dispatchem nefunguje, tzn. pokud použiji naja.uiHandler.submitForm(element), tak po přenačtení snippetů jinou metodou je problém. Pokud ovšem používám jenom třídu např. ajax a nepoužívám manual dispatch, tak je vše v pořádku.

**Comment by jiripudil** [comment]
After some discussion over PM, it seems most likely not to be an issue with Naja.
