### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by jkuchar** [jiripudil/Naja#23]
Are you considering supporting TypeScript / TypeScript definitions?

**Comment by jiripudil** [comment]
Yes, I have in progress some major changes, and while I'll be at it, I'm planning to rewrite Naja in TypeScript. That's going to take some time though, so for the time being, I'll happily accept a pull request with type definitions 😉

**Comment by jkuchar** [comment]
For those who need to get it "working" now, just use 

```typescript
// @ts-ignore no support for TypeScript yet, follow https://github.com/jiripudil/Naja/issues/23
import naja from 'naja';
```

**Comment by rozsival** [comment]
Hey there, since today `@types/naja` is available in the npm registry (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39092).

Once TS support is officially available in naja, we can deprecate that module.

Hope it helps!

**Comment by rozsival** [comment]
Do any of you guys find the `@types/naja` package useful? I'm using it on a few of my own projects and it works good for me. Just curious if it suits other projects too so the typings cover Naja's public API correctly.

@jiripudil Maybe this issue could be closed for now?

**Comment by jiripudil** [comment]
Hello @rozsival, thanks for your effort, it's awesome! And yes, we can indeed close this issue. Btw Naja 2.0 (coming soon™️, see #25) is going to bundle its own type definitions :wink:

**Comment by rozsival** [comment]
Great! Always glad to help. As mentioned before, once Naja has its own typings included, I will [remove](https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package) the `@types/naja` package.

**Comment by rozsival** [comment]
Hey @jiripudil, I've just submitted a new [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47001) for removing the stub types for `naja`.

**Comment by jiripudil** [comment]
Thank you, and thanks again for your work on the 1.x type definitions! I hope you'll enjoy Naja 2.0.0

**Comment by rozsival** [comment]
@jiripudil Thank you as well! I'm sure I will enjoy the new version.
