### ISSUE TITLE
Get event target in success event

### ISSUE THREAD

**Issue by apincik** [jiripudil/Naja#3]
Hello, i would like to implement custom event on element, which triggered ajax request for additional action like hiding modal after sucess ajax request etc. But i struggle getting original eventTarget, it's possible trough $(event.target) in "start" but it get lost later in "success".

```
function EventDOMExtension(naja, id) {
            naja.addEventListener('init', function () {
                this.selector = $(id);
            }.bind(this));

            naja.addEventListener('success', onSuccess.bind(this));

            function onSuccess() {
                this.selector.trigger('onSuccess');
            }

            return this;
        }

        naja.registerExtension(EventDOMExtension, "#descForm");

        $("#myForm").bind('onSuccess', function() {
            console.log("hide modal...")
        });
```

Not sure if this solution is the right one, thanks for advice. Result should be, get element onSuccess() without passing selector. Or possible feature, firing this "custom event" automatically in naja on UI.

**Comment by jiripudil** [comment]
I think the approach is quite good in general.

Note that `init` is dispatched only on the initial page load, so if the `#descForm` is added to the page via AJAX, it might not be in the DOM on `init`. You can use the `load` event which is dispatched both on the initial page load and after every AJAX request.

But you don't need that anyway - you can use the `interaction` event. It is dispatched when the user triggers the `.ajax` element and contains the element in `event.element`:

```js
function EventDOMExtension(naja, id) {
            naja.addEventListener('interaction', function (event) {
                this.element = event.element;
            }.bind(this));

            naja.addEventListener('success', onSuccess.bind(this));

            function onSuccess() {
                this.element.trigger('onSuccess');
            }

            return this;
        }

        naja.registerExtension(EventDOMExtension);

        $("#myForm").bind('onSuccess', function() {
            console.log("hide modal...")
        });
```

**Comment by apincik** [comment]
```
naja.addEventListener('interaction', onInteraction.bind(this));
function onInteraction() {
    selectorId = event.target.id;
}
```

Possible solution, anyway logical approach. Thanks

**Comment by jiripudil** [comment]
You're welcome :)
