### ISSUE TITLE
Submitter should be left out from data if its name is empty

### ISSUE THREAD

**Issue by jiripudil** [jiripudil/Naja#333]
# Bug Report

As reported on [Nette Forum](https://forum.nette.org/cs/34517-naja-data-ajax-append-a-historie#p216217), Naja [adds the submitter](https://github.com/jiripudil/Naja/blob/bd5600d0645a5f89563d0d74e49351d424e07511/src/core/UIHandler.ts#L109) to the form data even if it has an empty name. According to the [HTML spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constructing-form-data-set), fields with an empty name should be omitted from the data set though.

**Comment by rajdama** [comment]
I can do this.

**Comment by jiripudil** [comment]
Sure, go ahead, thank you!

Essentially it should suffice to

- add `element.name !== ''` to the condition (while you're at it, I think the `|| element.tagName === 'BUTTON'` part is a bug too and should be removed), and
- update the `element.type === 'image'` branch so that it appends just `x` and `y` _without the dot_ if `element.name === ''`.

**Comment by rajdama** [comment]
Noted 👍
