### ISSUE TITLE
README – unsupported IE listed

### ISSUE THREAD

**Issue by dakur** [jiripudil/Naja#51]
Readme still lists IE in supported browsers.

![image](https://user-images.githubusercontent.com/9862581/72522369-d1ba8f80-385d-11ea-8b31-90e291a8f7e0.png)

**Comment by jiripudil** [comment]
Correct, IE support is still provided in 1.x releases (which *is* the current master branch) and will only be dropped in the upcoming 2.0 which doesn't have a stable release yet.

On a side note: Saucelabs's widget unfortunately only shows the latest build no matter which branch it is, so the matrix in README might not always show the latest master. But that's not the case here.

**Comment by dakur** [comment]
@jiripudil But I am talking about 2.0. So maybe it's the Saucelabs issue.

![image](https://user-images.githubusercontent.com/9862581/72528228-da659280-386a-11ea-9d69-2fd36fddf061.png)

**Comment by jiripudil** [comment]
Oh, that wasn't apparent :) in that case, yes, that's an issue with the Saucelabs widget. I don't like it either, but I haven't yet found a way to work around it.
