### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by mira-kovar** [jiripudil/Naja#57]
Ahoj,
prosím jak můžu nastavit vyšší timeout než 30s v dokumentaci jsem to nikde nenašel.
Díky.

**Comment by jiripudil** [comment]
Ahoj, timeout je jedno z nastavení knihovny [`qwest`](https://github.com/pyrsmk/qwest#basics), která v Naje provádí AJAXové požadavky. Předávám do ní celé `options`, takže jej lze přenastavit třeba v defaultOptions:

```js
naja.defaultOptions.timeout = 60000; //ms
```

**Comment by mira-kovar** [comment]
Super. Díky to by  si zasloužilo přidat do dokumentace.
