### ISSUE TITLE
Submitting forms via GET does not send values

### ISSUE THREAD

**Issue by jiripudil** [jiripudil/Naja#61]
As reported [on slack](https://pehapkari.slack.com/archives/C2R30BLKA/p1587132987173100), forms submitted via `GET` do not serialize their values into the query string, effectively *not* sending the values at all.

Let's investigate if enforcing `POST` is feasible, as it is much easier and less prone to future bugs than manipulating the query string.

**Comment by jaroslavlibal** [comment]
In my particular case, it was "necessary" to keep the QS parameters, so the option with enforcing `POST` would not solve my issue. It was some kind of search-url builder form.
