### ISSUE TITLE
makeRequest appends url to current url

### ISSUE THREAD

**Issue by dakorpar** [jiripudil/Naja#64]
So I've tried to do this:
`naja.makeRequest('get', '/user/edit');`
but this actually loads
`http://site.com/currentpage/"user/edit"`

`naja.makeRequest('get', 'http://site.com/user/edit');`

tries to load 
`http://site.com/currentpage/"http://site.com/user/edit"`

**Comment by jiripudil** [comment]
Hello, which version is that? Does it do that in any particular browser, or all of them?

Could you prepare a repo which I could checkout and reproduce the behaviour? (Feel free to use my sandbox and try to break it.)

**Comment by dakorpar** [comment]
@jiripudil sorry to much work latelly 😆  all ok, I had quotes in code before and plink which added another quotes

**Comment by jiripudil** [comment]
No problem, good to hear it's resolved :)
