### ISSUE TITLE
Naja 2.0 - disabling history - not function

### ISSUE THREAD

**Issue by plany-a1** [jiripudil/Naja#85]
# Support Question
Hi, 
in naja.initialize does not function  option **history: false**. 
naja.initialize({
        history: false
    });
After settings this option browser show error **TypeError: right-hand side of 'in' should be an object, got boolean** 
Error is in HistoryHandler.js is: 
if ('history' in defaultOptions && 'uiCache' in defaultOptions.history) {
	this.uiCache = defaultOptions.history.uiCache;
}
In Naja 1.8 it was function.
In documentation (https://naja.js.org/#/dispatch) it is possible to use it. There is for example
naja.initialize({
    history: false,
    myCustomOption: 42,
    fetch: {
        credentials: 'same-origin',
    },
});
Thanks.

**Comment by jiripudil** [comment]
Hello, that looks like a bug. Thanks for the report!

**Comment by dakur** [comment]
We use `{history: false}` option with `makeRequest()` and that seems to work correctly.
